import Foundation

/// POC 3: "Hack" 方式原生 PPTX XML 注入生成
/// 目標：直接操作 PPTX 的 ZIP 結構與 XML，實現原生生成可編輯 PPTX
class NativePPTXGenerator {
    
    // PPTX 的座標單位是 EMUs (English Metric Units)
    // 1 英吋 = 914400 EMUs
    let emuPerInch: Int = 914400
    
    /// 生成一個 XML 文字塊節點
    /// - Parameters:
    ///   - text: 內容
    ///   - x: X 座標 (像素)
    ///   - y: Y 座標 (像素)
    ///   - cx: 寬度 (像素)
    ///   - cy: 高度 (像素)
    ///   - dpi: 圖片解析度 (用於換算英吋)
    func generateTextBoxXML(text: String, x: Double, y: Double, cx: Double, cy: Double, dpi: Double = 300) -> String {
        let xEMU = Int((x / dpi) * Double(emuPerInch))
        let yEMU = Int((y / dpi) * Double(emuPerInch))
        let cxEMU = Int((cx / dpi) * Double(emuPerInch))
        let cyEMU = Int((cy / dpi) * Double(emuPerInch))
        
        return """
        <p:sp>
            <p:nvSpPr>
                <p:cNvPr id="2" name="TextBox_AutoGenerated"/>
                <p:cNvSpPr txBox="1"/>
                <p:nvPr/>
            </p:nvSpPr>
            <p:spPr>
                <a:xfrm>
                    <a:off x="\(xEMU)" y="\(yEMU)"/>
                    <a:ext cx="\(cxEMU)" cy="\(cyEMU)"/>
                </a:xfrm>
                <a:prstGeom prst="rect">
                    <a:avLst/>
                </a:prstGeom>
                <a:noFill/>
            </p:spPr>
            <p:txBody>
                <a:bodyPr rtlCol="0" anchor="ctr"/>
                <a:lstStyle/>
                <a:p>
                    <a:r>
                        <a:rPr lang="zh-CN" sz="1200"/>
                        <a:t>\(text)</a:t>
                    </a:r>
                </a:p>
            </p:txBody>
        </p:sp>
        """
    }

    /// 模擬 PPTX 模板注入過程
    /// 在實際 App 中，我們會使用 ZIPFoundation 或 AppleArchive 解壓 -> 替換 -> 壓縮
    func injectToSlide(originalXML: String, textBoxes: [String]) -> String {
        // 在 PPT 中，所有圖形都在 <p:spTree> 標籤內
        let anchor = "</p:spTree>"
        let combinedText = textBoxes.joined(separator: "\n")
        return originalXML.replacingOccurrences(of: anchor, with: combinedText + anchor)
    }

    /// 演示轉換公式
    func runPoC3Demo() {
        print("🚀 執行 PoC 3: PPTX 佈局精準映射驗證")
        let xml = generateTextBoxXML(text: "石油化工IT架構藍圖", x: 100, y: 150, cx: 400, cy: 50)
        print("—— 生成的 XML 片段 (EMUs) ——")
        print(xml)
        print("——————————————————————————")
        print("✅ 佈局計算完成：座標已精準轉換為 \(emuPerInch) EMU 基準單位")
    }
}

// —— 測試執行邏輯 ——
let generator = NativePPTXGenerator()
generator.runPoC3Demo()
print("✅ PoC 3: NativePPTXGenerator 已完成邏輯驗證")
